- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Update Cache & Upgrade Apt
      apt:
        update_cache: true
        upgrade: yes
        autoremove: true

    - name: Install Software
      apt:
        name: "{{ item }}"
      with_items:
        - spotify-client
        - grub-customizer

    - name: Delete Trash Files
      file:
        path: ./playbook.software.retry
        state: absent
