- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: pull docker images
      command: docker pull {{ item }}
      with_items:
       - alpine
       - php:7-fpm-alpine
       - golang:1.10.3
       - consul:1.0.6
       - gliderlabs/registrator
       - rtlsabuc/php71:7.1.15-0

    - name: delete trash files
      file:
        path: ./playbook.docker.retry
        state: absent

