- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: pull docker images
      command: docker pull {{ item }}
      with_items:
       - ubuntu:16.04
       - alpine:3.7
       - mongo:3.6
       - mariadb:10.2
       - php:7.1.12-alpine
       - golang:1.9.2-alpine
       - consul:1.0.6
       - gliderlabs/registrator

    - name: delete trash files
      file:
        path: ./playbook.docker.retry
        state: absent
