- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: update cache
      apt:
        update_cache: true
        upgrade: no
        autoremove: no

    - name: pull docker images
      command: docker pull {{ item }}
      with_items:
       - ubuntu:16.04
       - alpine:3.5
       - mongo:3.4
       - mariadb:10.2
       - php:7.1.12-fpm-alpine
       - golang:1.8.5-alpine

    - name: delete trash files
      file:
        path: ./playbook.docker.retry
        state: absent
