- hosts: localhost
  become: true
  connection: local

  tasks:
    - name: development dependencies
      apt:
        name: "{{ item }}"
      with_items:
        - software-properties-common
        - python-pip
        - curl
        - git
        - git-core
        - htop

    - name: python dependencies
      pip:
        name: docker-py

    - name: programming languages
      apt:
        name: '{{ item }}'
      with_items:
        - default-jre
        - default-jdk
        - golang-go
        - php7.1
        - php7.1-common
        - php7.1-imap
        - php7.1-odbc
        - php7.1-soap
        - php7.1-xml
        - php7.1-curl
        - php7.1-mbstring
        - php7.1-opcache
        - php7.1-readline
        - php7.1-cgi
        - php7.1-dba
        - php7.1-mcrypt
        - php7.1-cli
        - php7.1-dev
        - php7.1-json
        - php7.1-mysql
        - php7.1-zip
        - php-mongodb
        - mongodb-org

    - name: delete trash files
      file:
        path: ./playbook.languajes.retry
        state: absent
